apps:
  - name : "koa"
    script : "app.js"
    # watch : true
#   instances : 2
    exec_mode : "cluster"
    env    :
      NODE_ENV: development
    env_production:
      NODE_ENV: production
    max_memory_restart : "4G"
    log_date_format : "YYYY-MM-DD HH:mm:SS"
